# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  startrabbit:
    cmds:
      - docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management || true
      - sleep 15
      - docker exec rabbitmq rabbitmqadmin declare exchange name=customer_events type=topic -u guest -p guest durable=true

  publish:
    cmds:
      - go run cmd/app/main.go publish {{.CLI_ARGS}}

  consume:
    cmds:
      - air -build.args_bin=consume {{.CLI_ARGS}}
#      - go run cmd/app/main.go consume

